// gen-build-info.ts — stamp the build with its source identity.
//
// Run just before `deno compile` (see the build tasks in deno.json). Queries jj
// for the commit id (git-sha, unique per snapshot) and the change id (stable
// across amends), with a git fallback and a final "unknown" so a build NEVER
// fails for lack of a VCS. Writes src/build-info.ts, which the engine imports and
// surfaces (start log, plan message, scan-debug journal, UI). This is what kills
// the "which exe is actually running?" ambiguity we hit chasing the outdated bug.
//
// src/build-info.ts is gitignored: it's a build artefact, regenerated every time,
// never committed (so the working copy never shows it as a spurious change).

async function run(cmd: string, args: string[]): Promise<string | null> {
  try {
    const { code, stdout } = await new Deno.Command(cmd, {
      args,
      stdout: "piped",
      stderr: "null",
    }).output();
    if (code !== 0) return null;
    const out = new TextDecoder().decode(stdout).trim();
    return out || null;
  } catch {
    return null; // cmd not on PATH (e.g. jj absent in a git-only CI)
  }
}

// commit id (git-sha) — jj first, then git, then unknown.
const sha =
  (await run("jj", ["log", "-r", "@", "--no-graph", "-T", "commit_id.short()"])) ??
    (await run("git", ["rev-parse", "--short", "HEAD"])) ??
    "unknown";

// change id — jj only (no git equivalent); "unknown" outside jj.
const change =
  (await run("jj", ["log", "-r", "@", "--no-graph", "-T", "change_id.short()"])) ??
    "unknown";

const builtAt = new Date().toISOString();

const body = `// GENERATED by scripts/gen-build-info.ts at build time — DO NOT EDIT, DO NOT COMMIT.
// Identifies the exact source snapshot this binary was compiled from.
export const BUILD = {
  sha: ${JSON.stringify(sha)}, // commit id (git-sha), unique per snapshot
  change: ${JSON.stringify(change)}, // jj change id, stable across amends
  builtAt: ${JSON.stringify(builtAt)}, // ISO timestamp of this build
} as const;
`;

const dest = new URL("../src/build-info.ts", import.meta.url);
await Deno.writeTextFile(dest, body);
console.error(`build-info: sha=${sha} change=${change} builtAt=${builtAt}`);
